version: '3.4'

services:
  sit7252022t3prac8:
    image: sit7252022t3prac8
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
